spring:
  cloud:
    config:
      enabled: true
      #远程仓库的分支
      label: master
      uri:  http://localhost:8763/
      name: monitor,common-eureka
      fail-fast: false
      username:
      password:
      #读取属性文件结尾
      profile: pro
