spring:
  cloud:
    config:
#      server 端配置
      server:
        git:
          uri: https://github.com/ChenHouZhen/spring-cloud-project.git
#          如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          username:
          password:
          search-paths: project-config/src/main/resources/**
          default-label: master
#          basedir: project-config/src/main/resources/**
          clone-on-start: true
          force-pull: true


# SpringCloud 配置
security:
  user:
    name: root
    password: root

hrc:
  url: project-eureka
  port: 8761

eureka:
  client:
    service-url:
      defauleZone: http://${security.user.name}:${security.user.password}@${hrc.url}:${hrc.port}/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    hostname: ${spring.application.name}
    # 实例使用ip进行访问
#    prefer-ip-address: true
    # 实例显示id
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    # 服务续约任务调用间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 2
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
    # 状态页面和健康指标
#    statusPageUrlPath: ${server.context-path}/swagger-ui.html