server:
  port: 8763

spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChenHouZhen/spring-cloud-project.git
#          如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          username:
          password:
          search-paths: project-config/src/main/resources/**
          default-label: master
#          basedir: project-config/src/main/resources/**
          clone-on-start: true
          force-pull: true
