spring:
  cloud:
    config:
      enabled: true
      #远程仓库的分支
      label: master
      uri:  http://localhost:8763/
      name: common-eureka
      fail-fast: false
      username:
      password:
      #读取属性文件结尾
      profile: dev
#      server 端配置
      server:
        git:
          uri: https://github.com/ChenHouZhen/spring-cloud-project.git
#          如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
          username:
          password:
          search-paths: project-config/src/main/resources/**
          default-label: master
#          basedir: project-config/src/main/resources/**
          clone-on-start: true
          force-pull: true
